### PR TITLE
uts: initial commit

### PR DESCRIPTION
**Pull request by joalsop**
Add UTS benchmark and related files.
TODO: debug driver issues

### CODE REVIEW

**Comment by mattsinc** [comment]
Thanks @joalsop!  What are the driver issues that need to be resolved?

Also, can you please include (even here) a snippet of how to run UTS?  I can create a run file then.  This will also need to go into the denovo sub-folder since it's the denovo specific version.  I can create a UVM version from this, but need to know what the driver issues and sample run is first.

**Comment by joalsop** [comment]
Sure thing - when running with cuda 3.1 it is failing on cudaMalloc of the uts tree (I'm curious if there are issues when running with newer GPU/CUDA versions)
error is: 
ERROR After cudaMalloc1 - unspecified driver error

usage is:
./uts <numThreads> <numElements> <fertility> <local_stack_size> <N_active_blocks>
where:
        <numThreads>: Number of CPU threads to launch
        <numElements>: Number of elements in the data array
        <fertility>: 1-100, percent chance that a node has children (for unbalanced tree generation)
        <local_stack_size>: if < 0, how many times to half the num nodes before getting aggregate local stack size. If > 0, what the maximum local stack size should be
        <N_active_blocks>: Number of threadblocks to use

example usage: ./uts 1 1024 90 32 1

**Comment by mattsinc** [comment]
Ok, thanks!

Will merge this in for now, move to under DeNovo, and then try with newer versions.

**Comment by mattsinc** [comment]
@joalsop : how long do expect UTS to run on a real GPU using the same input args you provided?

I have ported the version of UTS you uploaded to use CUDA UVM (mostly by converting cudaMalloc to cudaMallocManaged, adding the appropriate fences in the lock/unlock functions, and adding a cudaDeviceSynchronize() after the kernel), compiled for Pascal and Volta, and am trying to run on a GTX 1080 with CUDA 11.  I am seeing the following:

[sinclair@koholint] (78)$ ./uts 1 1024 90 32 1
got threads:1
Running with N_elements=1025 N_active_blocks=1
done processing nodes
done initing work stack
Launch uts kernel...

It seems to run the UTS kernel for a very long time though.  Is this expected?

Either way, for Pascal, the issue you highlighted does not seem to be a problem.

**Pull request merged**
